### ISSUE TITLE
Authentication error when trying to save analysis results

### ISSUE THREAD

**Issue by CarolinH4** [Ericsson/codechecker#2706]
Hi,

we successfully established authentication for CodeChecker.
But now, when trying to save previously created analysis results, we get the following error:

[ERROR 2020-04-07 13:13] - Internal server error: Error code 401: Unauthorized!

Without authentication, saving analysis results works as expected.

Steps to reproduce:

* Activate authentication in configuration file ~/.codechecker/server_config.json:
```
"authentication" : {
    "enabled" : true ,
    "realm_name" : "CodeChecker Privileged server",
    "realm_error" : "Access requires valid credentials.",
    "session_lifetime" : 300,
    "refresh_time" : 60,
    "logins_until_cleanup" : 30,
    "method_dictionary": {
      "enabled" : true,
      "auths" : [
        "admin_usr:<admin_usr_password>", "view_usr:<view_usr_password>" 
      ],
      "groups" : {
        "admin_usr" : ["admin"],
        "view_usr" : ["guest"]
      }
    },
```
* Activate auto login in .codechecker.passwords.json:
```
{
  "client_autologin" : true,
  "credentials": {
    "*" : "admin_usr:<admin_usr_password>" 
  }
}
```
* Stop CodeChecker:
`CodeChecker server --stop-all`
* Start CodeChecker:
`CodeChecker server -w ~/.codechecker --not-host-only > /dev/null 2>&1 &`
* Store analysis results, e.g.:
`CodeChecker store core_results -n <analysis_name> --url <product_url>`

**Comment by csordasmarton** [comment]
- @CarolinH4 What is your CodeChecker version (`CodeChecker version`)?
- What is the output of your store command (try to run it with the `--verbose debug` option)?

**Comment by CarolinH4** [comment]
* @csordasmarton  Version:
`CodeChecker analyzer version:
---------------------------------------------------------------
Kind                 | Version
---------------------------------------------------------------
Base package version | 6.11.1
Package build date   | 2020-03-10T15:06
Git commit ID (hash) | 9bb0047368707a18efaca3a207dc8227c8e19b9e
Git tag information  | 6.11.1
---------------------------------------------------------------

CodeChecker web version:
------------------------------------------------------------------------
Kind                          | Version
------------------------------------------------------------------------
Base package version          | 6.11.1
Package build date            | 2020-03-10T15:06
Git commit ID (hash)          | 9bb0047368707a18efaca3a207dc8227c8e19b9e
Git tag information           | 6.11.1
Server supported API (Thrift) | 6.24
Client API (Thrift)           | 6.24
------------------------------------------------------------------------
`
* CodeChecker store output:
[CodeChecker_Store_Output.txt](https://github.com/Ericsson/codechecker/files/4552123/CodeChecker_Store_Output.txt)

**Comment by csordasmarton** [comment]
@CarolinH4 I think it will be a bug in the CodeChecker. The problem is that you have an expired session token and in this case we will not check if this token is expired or not:
https://github.com/Ericsson/codechecker/blob/123b83aeb92d69749f9520e41e1a9167e03533fc/web/client/codechecker_client/client.py#L229-L233

It should be fixed in our side. Now what you can do is to run the `CodeChecker cmd login` command before the store command and it will generate a new session token for you.

**Comment by CarolinH4** [comment]
@csordasmarton Thanks for your help!

Unfortunately, calling _cmd login_ before the _store_ call, didn't solve the problem.
What I found out now is, that it works when specifying _localhost:<port>_ in the argument _--url_ - instead of putting the full hostname here. This also works without the call of cmd login...

**Comment by csordasmarton** [comment]
@CarolinH4 How does you url looks like? A couple of days ago we found a problem that saved credentials are not worked properly when the url contains a special non word character. For example: https://codechecker-demo.cloudapp.azure.com/. Maybe your problem is related to this one. See the solution: #2704.

**Comment by CarolinH4** [comment]
Our url looks like the following: http://host4.spec.additional:8001/Product

**Comment by csordasmarton** [comment]
What happens if you do the following:
- logout from the server: `CodeChecker cmd login -d --url http://host4.spec.additional:8001/Product`
- login to the server: `CodeChecker cmd login --url http://host4.spec.additional:8001/Product`
- store results to the server: `CodeChecker store core_results -n <analysis_name> --url http://host4.spec.additional:8001/Product`

**Comment by CarolinH4** [comment]
Hmm alright, it works now - with only calling:
_CodeChecker store core_results -n <analysis_name> --url http://host4.spec.additional:8001/Product_
No prior logout/login needed any more.

Do you have any idea why the issue doesn't occur any more?

**Comment by csordasmarton** [comment]
@CarolinH4 I think your token is not expired so this is the reason it works now. The expiration time can be configured on the server by the [`session_lifetime` ](https://github.com/Ericsson/codechecker/blob/afc73ed9ffba37286a08a28079861fc41943ea08/docs/web/authentication.md) key: the lifetime of the session sets that after this many seconds since last session access the session is permanently invalidated. So if you use this token (using web browser or command line client), it will never expire.

As I mentioned above this will be a bug in our code, that we do not autologin the user when a session is expired even if the credentials are configured properly, so we will try to find a solution for this problem as soon as possible.

**Comment by CarolinH4** [comment]
@csordasmarton OK, I understand. Many thanks for the workarounds! Using the _session_lifetime_ works now for us.

**Comment by csordasmarton** [comment]
@CarolinH4 I forgot one more thing. Instead of write and use your own password in the `.codechecker.passwords.json` file you can generate a [personal access token](https://github.com/Ericsson/codechecker/blob/master/docs/web/authentication.md#personal-access-token) and use it instead of your password. It will solve your problem too because these tokens will never expire.

**Comment by CarolinH4** [comment]
@csordasmarton Thanks! I implemented this using personal access token - works fine... :)
